# ATTENTION DEVELOPER:
#
# When this service is ready to be built and deployed along with the other microservices, the following must occur
#
# 1. Rename this file to "retail.yml"
# 2. Remove this comment block.
# 3. Add the file to the ssp-configuration-repo Git repository under the "ms" branch.
# 4. Start this service to confirm it obtains its configuration.
#

management.security.enabled: false
security.basic.enabled: false

server:
  port: 9101
  contextPath: /retail

oauth2:
  resource:
     jwt:
        keyValue: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmhAyldeztFrQGG1gYKe1
           igqPt9kpoFBzk+66m/rlqUkahwB2aAfJJIUH7iQnKkX9qNTiu1m9ux/qBSMSzHs5
           ZwN7DLjugwUy0XDt98QTPlLLBJALLibJCz+ag+wiMBW4GF14mHGg3sDjnrc70t3j
           ouYCZX9T6lgRxo9rH7XaCEzK7W/uPIKZLML0JtTc9cEYkYNvxkb8xPspaXtl7lHi
           XoX7zGoUO2OOQ2gG4wiYAQt1BbuU9KrCpRPTT0m3XOgPm2yKzSx6Z3/Ev88fcpVe
           ebku6B9cjBl/tkSSP+s1k4dB4yMrkcWXZBRVaPDp6c0nF+Rsq74R7NUrDPSPy+/D
           qQIDAQAB
           -----END PUBLIC KEY-----

---
spring:
  profiles: dev
  cloud:
    discovery:
      enable: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://db:3306/retail?tinyInt1isBit=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: tenxdev
    driver-class-name: com.mysql.jdbc.Driver
